# Preprocessing data

### Standardization, or mean removal and variance scaling


Standardization of datasets is a common requirement for many machine learning estimators implemented in scikit-learn; 

In practice we often ignore the shape of the distribution and just transform the data to center it by removing the mean value of each feature, then scale it by dividing non-constant features by their standard deviation.



In [7]:
from sklearn import preprocessing
import numpy as np
import pandas as pd

X_train = np.array([[ 1., -1.,  2.],
                    [ 2.,  0.,  0.],
                    [ 0.,  1., -1.]])

X_scaled = preprocessing.scale(X_train) # non viene utilizzato questo metodo

X_scaled     

array([[ 0.        , -1.22474487,  1.33630621],
       [ 1.22474487,  0.        , -0.26726124],
       [-1.22474487,  1.22474487, -1.06904497]])

In [8]:
X_train.std(axis=0) # deviazione std

array([0.81649658, 0.81649658, 1.24721913])

In [9]:
X_train.mean(axis=0)

array([1.        , 0.        , 0.33333333])

In [10]:
X_scaled.mean(axis=0)

array([0., 0., 0.])

In [11]:
X_scaled.std(axis=0)

array([1., 1., 1.])

The standard score of a sample x is calculated as:
<tt>z = (x - u) / s</tt>
where u is the mean of the training samples or zero if <tt>with_mean=False</tt>, and s is the standard deviation of the training samples or one if <tt>with_std=False</tt>.


The preprocessing module further provides a utility class StandardScaler that implements the Transformer API to compute the mean and standard deviation on a training set so as to be able to later reapply the same transformation on the testing set.

In [12]:
sss = preprocessing.StandardScaler() # si istanzia il modello che si vuole usare
scaler = sss.fit(X_train)

In [13]:
scaler

StandardScaler()

In [14]:
scaler.mean_ 

array([1.        , 0.        , 0.33333333])

In [15]:
scaler.scale_ 

array([0.81649658, 0.81649658, 1.24721913])

In [16]:
newX_Train = scaler.transform(X_train) 

In [17]:
scaler.fit(X_train) #
scaler.transform(X_train) # per l'andamento del modello stesso

array([[ 0.        , -1.22474487,  1.33630621],
       [ 1.22474487,  0.        , -0.26726124],
       [-1.22474487,  1.22474487, -1.06904497]])

In [18]:
scaler.fit_transform(X_train) # abbiamo il dataset nella sua interezza

array([[ 0.        , -1.22474487,  1.33630621],
       [ 1.22474487,  0.        , -0.26726124],
       [-1.22474487,  1.22474487, -1.06904497]])

In [19]:
scaler.fit_transform(X_train).mean()

4.9343245538895844e-17

In [20]:
scaler.fit_transform(X_train).std()

1.0

The scaler instance can then be used on new data to transform it the same way it did on the training set



In [21]:
X_test = [[-1., 1., 0.]]
scaler.transform(X_test)    

array([[-2.44948974,  1.22474487, -0.26726124]])

### Scaling features to a range

An alternative standardization is scaling features to lie between a given minimum and maximum value, often between zero and one, or so that the maximum absolute value of each feature is scaled to unit size.

In [22]:
# il KNN deve prima essere normalizzato:
X_train = np.array([[ 1., -1.,  2.],
                    [ 2.,  0.,  0.],
                    [ 0.,  1., -1.]])

In [23]:
X_train

array([[ 1., -1.,  2.],
       [ 2.,  0.,  0.],
       [ 0.,  1., -1.]])

In [24]:
min_max_scaler = preprocessing.MinMaxScaler((0,1)) # default [0,1]

In [25]:
min_max_scaler.fit(X_train)

MinMaxScaler()

In [26]:
min_max_scaler.transform(X_train)

array([[0.5       , 0.        , 1.        ],
       [1.        , 0.5       , 0.33333333],
       [0.        , 1.        , 0.        ]])

In [27]:
X_train_minmax = min_max_scaler.fit_transform(X_train)

In [28]:
X_train_minmax

array([[0.5       , 0.        , 1.        ],
       [1.        , 0.5       , 0.33333333],
       [0.        , 1.        , 0.        ]])

In [29]:
X_test = np.array([[-3., -1.,  4.]])
X_test_minmax = min_max_scaler.transform(X_test)
X_test_minmax

array([[-1.5       ,  0.        ,  1.66666667]])

In [30]:
X_train.mean()

0.4444444444444444

In [31]:
X_train_minmax.mean()

0.48148148148148145

In [32]:
X_train.std()

1.0657403385139377

In [33]:
X_train_minmax.std()

0.4115946439054235

The transformation is computed as:

<tt>X_scaled = scale * X + min - X.min(axis=0) * scale</tt>

where <tt>scale = (max - min) / (X.max(axis=0) - X.min(axis=0))</tt>

In [34]:
min_max_scaler.scale_  

array([0.5       , 0.5       , 0.33333333])

If your data contains many outliers, scaling using the mean and variance of the data is likely to not work very well. In these cases, you can use robust_scale and RobustScaler (x_scaled = x / max(abs(x)))
as drop-in replacements instead. They use more robust estimates for the center and range of your data.



In [35]:
from sklearn.preprocessing import RobustScaler
X = [[ 1., -2.,  2.],
     [ -2.,  1.,  3.],
     [ 4.,  1., -2.]]


In [36]:
transformer = RobustScaler().fit(X)

In [37]:
transformer  

RobustScaler()

In [38]:
transformer.scale_

array([3. , 1.5, 2.5])

In [39]:
transformer.transform(X)

array([[ 0. , -2. ,  0. ],
       [-1. ,  0. ,  0.4],
       [ 1. ,  0. , -1.6]])

## Normalization


Normalization is the process of scaling individual samples to have unit norm. This process can be useful if you plan to use a quadratic form such as the dot-product or any other kernel to quantify the similarity of any pair of samples.

‘l1’
The l1 norm uses the sum of all the values as and thus gives equal penalty to all parameters, enforcing sparsity.
x_normalized = x / sum(X)


‘l2’
The l2 norm uses the square root of the sum of all the squared values. This creates smoothness and rotational invariance. Some models, like PCA, assume rotational invariance, and so l2 will perform better.
x_normalized = x / sqrt(sum((i**2) for i in X))

In [40]:
# Normalization -> lavora sulle righe, lavorando in orrizzontale
X = np.array([[1., -1.,  2.],
     [ 2.,  0.,  0.],
     [ 0.,  1., -1.]])
X_normalized = preprocessing.normalize(X, norm='l1')

In [41]:
# the same as previous X_normalized = preprocessing.Normalizer(norm='l2').fit_transform(X)

In [42]:
X_normalized                                      

array([[ 0.25, -0.25,  0.5 ],
       [ 1.  ,  0.  ,  0.  ],
       [ 0.  ,  0.5 , -0.5 ]])

In [43]:
np.sqrt(0.40824829**2 + 0.40824829**2 + 0.81649658**2)

0.9999999988637723

You can refer to [https://scikit-learn.org/stable/auto_examples/preprocessing/plot_all_scaling.html](https://scikit-learn.org/stable/auto_examples/preprocessing/plot_all_scaling.html) for more details.

##  Encoding categorical features

In [44]:
X = [['male', 'from US', 'uses Safari'], 
     ['female', 'from Europe', 'uses Firefox']]


In [45]:
enc = preprocessing.OneHotEncoder()
X = [['male', 'from US', 'uses Safari'], ['female', 'from Europe', 'uses Firefox']]
enc.fit(X)

OneHotEncoder()

In [46]:
enc = preprocessing.OneHotEncoder(handle_unknown='error', sparse=True)
X = [['male', 'from US', 'uses Safari'], ['female', 'from Europe', 'uses Firefox']]
enc.fit(X)

OneHotEncoder(sparse_output=False)

In [47]:
enc.get_feature_names_out()

array(['x0_female', 'x0_male', 'x1_from Europe', 'x1_from US',
       'x2_uses Firefox', 'x2_uses Safari'], dtype=object)

In [48]:
enc.transform([['female', 'from US', 'uses Safari'],
               ['male', 'from Europe', 'uses Firefox']]).toarray()

AttributeError: 'numpy.ndarray' object has no attribute 'toarray'

In [ ]:
enc.transform([['male', 'from US', 'uses Safari'], ['female', 'from Europe', 'uses Firefox']]).toarray()

In [ ]:
enc.categories_

In [ ]:
new_features = []
for i in enc.categories_:
  for j in i:
    print(j)
    new_features.append(j)

print(new_features)

In [ ]:
pd.DataFrame(X, columns=['gender', 'locations', 'browser'])

In [ ]:
X = [['male', 'from Asia', 'uses Safari'], ['female', 'from Europe', 'uses Firefox'], ['male', 'from Asia', 'uses Safari']]
enc.fit(X)

new_features = []
for i in enc.categories_:
  for j in i:
    new_features.append(j)


Xnew = enc.transform(X).toarray()
pd.DataFrame(Xnew, columns=new_features)

In [ ]:
enc.categories_

with fixed categories value

In [49]:
genders = ['female', 'male']
locations = ['from Africa', 'from Asia', 'from Europe', 'from US']
browsers = ['uses Chrome', 'uses Firefox', 'uses IE', 'uses Safari']
enc = preprocessing.OneHotEncoder(categories=[genders, locations, browsers])

# Note that for there are missing categorical values for the 2nd and 3rd
# feature


X = [['male', 'from US', 'uses Safari'], ['female', 'from Europe', 'uses Firefox']]
enc.fit(X) 

OneHotEncoder(categories=[['female', 'male'],
                          ['from Africa', 'from Asia', 'from Europe',
                           'from US'],
                          ['uses Chrome', 'uses Firefox', 'uses IE',
                           'uses Safari']])

In [50]:
enc.transform([['female', 'from Asia', 'uses Chrome']]).toarray()


array([[1., 0., 0., 1., 0., 0., 1., 0., 0., 0.]])

with unknown values

In [52]:
enc = preprocessing.OneHotEncoder(handle_unknown='ignore', sparse=True)
X = [['male', 'from US', 'uses Safari'], ['female', 'from Europe', 'uses Firefox']]
enc.fit(X) 

OneHotEncoder(handle_unknown='ignore', sparse_output=False)

In [55]:
enc.transform([['female', 'from Asia', 'uses Chrome']]).toarray()

AttributeError: 'numpy.ndarray' object has no attribute 'toarray'

drop first

In [57]:
X = [['male', 'from US', 'uses Safari'], ['female', 'from Europe', 'uses Firefox'], ['male', 'from Asia', 'uses Safari'], ['male', 'from Indo', 'uses Safari']]
drop_enc = preprocessing.OneHotEncoder(drop='first').fit(X)

In [58]:
drop_enc.categories_

[array(['female', 'male'], dtype=object),
 array(['from Asia', 'from Europe', 'from Indo', 'from US'], dtype=object),
 array(['uses Firefox', 'uses Safari'], dtype=object)]

In [59]:
drop_enc.transform(X).toarray()

array([[1., 0., 0., 1., 1.],
       [0., 1., 0., 0., 0.],
       [1., 0., 0., 0., 1.],
       [1., 0., 1., 0., 1.]])

In [62]:
X

[array(['female', 'male'], dtype=object),
 array(['from Asia', 'from Europe', 'from Indo', 'from US'], dtype=object),
 array(['uses Firefox', 'uses Safari'], dtype=object)]

## Discretization

Discretization (otherwise known as quantization or binning) provides a way to partition continuous features into discrete values. Certain datasets with continuous features may benefit from discretization, because discretization can transform the dataset of continuous attributes to one with only nominal attributes.

In [63]:
X = np.array([[ -3., 5., 15 ],
              [  0., 6., 14 ],
              [  6., 3., 11 ]])
est = preprocessing.KBinsDiscretizer(n_bins=[3, 2, 3], encode='ordinal').fit(X)
est

KBinsDiscretizer(encode='ordinal', n_bins=[3, 2, 3])

In [64]:
est.transform(X)   

array([[0., 1., 2.],
       [1., 1., 1.],
       [2., 0., 0.]])

There are different strategies implemented in KBinsDiscretizer:

- ‘uniform’: The discretization is uniform in each feature, which means that the bin widths are constant in each dimension.

- quantile’: The discretization is done on the quantiled values, which means that each bin has approximately the same number of samples.

- ‘kmeans’: The discretization is based on the centroids of a KMeans clustering procedure.

https://scikit-learn.org/stable/auto_examples/preprocessing/plot_discretization_strategies.html?highlight=kbinsdiscretizer

Feature binarization is the process of thresholding numerical features to get boolean values. This can be useful for downstream probabilistic estimators that make assumption that the input data is distributed according to a multi-variate Bernoulli distribution.

In [65]:
X = [[ 1., -1.,  2.],
     [ 2.,  0.,  0.],
     [ 0.,  1., -1.]]

binarizer = preprocessing.Binarizer().fit(X)  # fit does nothing
binarizer

Binarizer()

In [66]:
binarizer.transform(X)

array([[1., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.]])

In [67]:
binarizer = preprocessing.Binarizer(threshold=1.1)

In [68]:
binarizer.transform(X)

array([[0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 0.]])

## Custom transformers

Often, you will want to convert an existing Python function into a transformer to assist in data cleaning or processing. 

In [69]:
import numpy as np
from sklearn.preprocessing import FunctionTransformer

transformer = FunctionTransformer(np.log1p, validate=True)
X = np.array([[0, 1], [2, 3]])
transformer.transform(X)

array([[0.        , 0.69314718],
       [1.09861229, 1.38629436]])

The *validate* parameter indicates that the input X array should be checked before calling func. The possibilities are:

- If False, there is no input validation.

- If True, then X will be converted to a 2-dimensional NumPy array or sparse matrix. If the conversion is not possible an exception is raised.

In [70]:
type(X)

numpy.ndarray

In [71]:
type(transformer.transform(X)) 

numpy.ndarray

In [72]:
df = pd.DataFrame(X)

In [73]:
df

0  1
0  0  1
1  2  3

In [74]:
transformer.transform(df)

array([[0.        , 0.69314718],
       [1.09861229, 1.38629436]])

In [75]:
transformer = FunctionTransformer(np.log1p, validate=False)

In [76]:
transformer.transform(df)

0         1
0  0.000000  0.693147
1  1.098612  1.386294

Pay Attention!
The result of a transformer is typically a np.array!

In [ ]:
preprocessing.StandardScaler().fit_transform(df)

In [ ]:
preprocessing.StandardScaler().fit_transform(X)