# 1 Scaricare il [dataset](https://archive.ics.uci.edu/ml/datasets/mushroom) e inserirlo nel dataframe

In [1]:
import pandas as pd

In [2]:
column_names = ['cap-shape','cap-surface','cap-color','bruises?','odor','gill-attachment','gill-spacing','gill-size','gill-color','stalk-shape','stalk-root','stalk-surface-above-ring','stalk-surface-below-ring','stalk-color-above-ring','stalk-color-below-ring','veil-type','veil-color','ring-number','ring-type','spore-print-color','population','habitat']
column_names

['cap-shape',
 'cap-surface',
 'cap-color',
 'bruises?',
 'odor',
 'gill-attachment',
 'gill-spacing',
 'gill-size',
 'gill-color',
 'stalk-shape',
 'stalk-root',
 'stalk-surface-above-ring',
 'stalk-surface-below-ring',
 'stalk-color-above-ring',
 'stalk-color-below-ring',
 'veil-type',
 'veil-color',
 'ring-number',
 'ring-type',
 'spore-print-color',
 'population',
 'habitat']

In [3]:
data = pd.read_csv("Data/agaricus-lepiota.csv")
data

p  x  s  n  t p.1  f  c n.1  k  ... s.2  w w.1 p.2 w.2  o p.3 k.1 s.3  u
0     e  x  s  y  t   a  f  c   b  k  ...   s  w   w   p   w  o   p   n   n  g
1     e  b  s  w  t   l  f  c   b  n  ...   s  w   w   p   w  o   p   n   n  m
2     p  x  y  w  t   p  f  c   n  n  ...   s  w   w   p   w  o   p   k   s  u
3     e  x  s  g  f   n  f  w   b  k  ...   s  w   w   p   w  o   e   n   a  g
4     e  x  y  y  t   a  f  c   b  n  ...   s  w   w   p   w  o   p   k   n  g
...  .. .. .. .. ..  .. .. ..  .. ..  ...  .. ..  ..  ..  .. ..  ..  ..  .. ..
8118  e  k  s  n  f   n  a  c   b  y  ...   s  o   o   p   o  o   p   b   c  l
8119  e  x  s  n  f   n  a  c   b  y  ...   s  o   o   p   n  o   p   b   v  l
8120  e  f  s  n  f   n  a  c   b  n  ...   s  o   o   p   o  o   p   b   c  l
8121  p  k  y  n  f   y  f  c   n  b  ...   k  w   w   p   w  o   e   w   v  l
8122  e  x  s  n  f   n  a  c   b  y  ...   s  o   o   p   o  o   p   o   c  l

[8123 rows x 23 columns]

In [4]:
target = data.iloc[:,0] # questa é la colonna del target
target

0       e
1       e
2       p
3       e
4       e
       ..
8118    e
8119    e
8120    e
8121    p
8122    e
Name: p, Length: 8123, dtype: object

In [6]:
mushroom = data.drop(data.columns[0],axis=1)

mushroom.columns = column_names
mushroom

cap-shape cap-surface cap-color bruises? odor gill-attachment  \
0            x           s         y        t    a               f   
1            b           s         w        t    l               f   
2            x           y         w        t    p               f   
3            x           s         g        f    n               f   
4            x           y         y        t    a               f   
...        ...         ...       ...      ...  ...             ...   
8118         k           s         n        f    n               a   
8119         x           s         n        f    n               a   
8120         f           s         n        f    n               a   
8121         k           y         n        f    y               f   
8122         x           s         n        f    n               a   

     gill-spacing gill-size gill-color stalk-shape  ...  \
0               c         b          k           e  ...   
1               c         b          n           e  ...   
2               c         n          n           e  ...   
3               w         b          k           t  ...   
4               c         b          n           e  ...   
...           ...       ...        ...         ...  ...   
8118            c         b          y           e  ...   
8119            c         b          y           e  ...   
8120            c         b          n           e  ...   
8121            c         n          b           t  ...   
8122            c         b          y           e  ...   

     stalk-surface-below-ring stalk-color-above-ring stalk-color-below-ring  \
0                           s                      w                      w   
1                           s                      w                      w   
2                           s                      w                      w   
3                           s                      w                      w   
4                           s                      w                      w   
...                       ...                    ...                    ...   
8118                        s                      o                      o   
8119                        s                      o                      o   
8120                        s                      o                      o   
8121                        k                      w                      w   
8122                        s                      o                      o   

     veil-type veil-color ring-number ring-type spore-print-color population  \
0            p          w           o         p                 n          n   
1            p          w           o         p                 n          n   
2            p          w           o         p                 k          s   
3            p          w           o         e                 n          a   
4            p          w           o         p                 k          n   
...        ...        ...         ...       ...               ...        ...   
8118         p          o           o         p                 b          c   
8119         p          n           o         p                 b          v   
8120         p          o           o         p                 b          c   
8121         p          w           o         e                 w          v   
8122         p          o           o         p                 o          c   

     habitat  
0          g  
1          m  
2          u  
3          g  
4          g  
...      ...  
8118       l  
8119       l  
8120       l  
8121       l  
8122       l  

[8123 rows x 22 columns]

# 2 Trasformare i valori degli attributi in numeri
Sarà necessario usare il OneHotEncoder oppure un OrdinalEncoder 

In [7]:
from sklearn.preprocessing import OneHotEncoder
enc = OneHotEncoder(sparse=False)
enc

OneHotEncoder(sparse=False)

In [8]:
X = enc.fit_transform(mushroom)

/usr/local/lib/python3.10/dist-packages/sklearn/preprocessing/_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(


In [12]:
X

array([[0., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       ...,
       [0., 0., 1., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

# 3 Calcolare l'accuratezza(5 folder cross validation) del dataset ottenuto nel predire se un fungo é velenoso con 3 classificatori

I 3 classificatori che utilizzo sono:
- Random Forest
- SVC
- KNN


In [10]:
from sklearn.ensemble import  RandomForestClassifier
from sklearn.neighbors import  KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.model_selection import cross_validate
# i modelli:
classifiers = [RandomForestClassifier(n_estimators=20),
               KNeighborsClassifier(weights="distance"),
               SVC(kernel='linear',C=0.1)]

names = ['Random Forest','KNN','SVC']

# le metriche:
scoring = ['precision_macro','recall_macro','accuracy']

for name,model in zip(names,classifiers):
    scoring_model = cross_validate(model, X, target, scoring=scoring, cv=5)
    print('scores of '+ name +' :' )
    print(scoring_model['test_accuracy'])

scores of Random Forest :
[0.84307692 1.         0.99630769 1.         0.8294335 ]
scores of KNN :
[0.84430769 1.         0.99569231 1.         0.79987685]
scores of SVC :
[0.88246154 1.         0.99569231 1.         0.57327586]


In [ ]:
import matplotlib.pyplot as plt
# fig, ax = plt.subplots(1, 1)
# ax.plot(score_knn['test_accuracy'], 'r', label='knn')
# ax.plot(score_rdm['test_accuracy'], 'b', label='Random Forest ')
# ax.plot(score_supv['test_accuracy'], 'k', label='svc')
#
#
# # Set Legend
# ax.legend(loc='best')
#
# # Set Title
# ax.set_title('Overview')
#
# # Set X and Y axis label
# ax.set_xlabel('k folder')
# ax.set_ylabel('Accuratezza')

# 4/5 Utilizzare solo gli attributi del dataset che riguardano il colore ( chiamare il nuovo dataset mushroom_color) e verificare se l'accuratezza cambia



In [13]:
colori =  [name for name in column_names if 'color' in name ]
colori

['cap-color',
 'gill-color',
 'stalk-color-above-ring',
 'stalk-color-below-ring',
 'veil-color',
 'spore-print-color']

In [14]:
mushroom_color = mushroom.loc[:,colori]

In [15]:
mushroom_color

cap-color gill-color stalk-color-above-ring stalk-color-below-ring  \
0            y          k                      w                      w   
1            w          n                      w                      w   
2            w          n                      w                      w   
3            g          k                      w                      w   
4            y          n                      w                      w   
...        ...        ...                    ...                    ...   
8118         n          y                      o                      o   
8119         n          y                      o                      o   
8120         n          n                      o                      o   
8121         n          b                      w                      w   
8122         n          y                      o                      o   

     veil-color spore-print-color  
0             w                 n  
1             w                 n  
2             w                 k  
3             w                 n  
4             w                 k  
...         ...               ...  
8118          o                 b  
8119          n                 b  
8120          o                 b  
8121          w                 w  
8122          o                 o  

[8123 rows x 6 columns]

In [16]:
from sklearn.pipeline import Pipeline

classifiers = [RandomForestClassifier(n_estimators=20),
               KNeighborsClassifier(weights="distance"),
               SVC(kernel='linear',C=0.1)]

names = ['Random Forest','KNN','SVC']

enc = OneHotEncoder(sparse=False)
mushroom_color_trasform = enc.fit_transform(mushroom_color)

for name,model in zip(names,classifiers):
    scoring_model = cross_validate(model, mushroom_color_trasform, target, scoring=scoring, cv=5)
    print('scores of '+ name +' :' )
    print(scoring_model['test_accuracy'])

/usr/local/lib/python3.10/dist-packages/sklearn/preprocessing/_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(


scores of Random Forest :
[0.74276923 0.94461538 0.96676923 0.99568966 0.59174877]
scores of KNN :
[0.74707692 0.99138462 0.99076923 1.         0.71305419]
scores of SVC :
[0.73415385 0.99015385 0.97907692 1.         0.52894089]


# 6 Aggiungere un attributo a mushrooom_color del punto 4 del dataset originale in modo da aumentare l’accuratezza
Aggiungere una colonna

In [17]:
mushroom_color

cap-color gill-color stalk-color-above-ring stalk-color-below-ring  \
0            y          k                      w                      w   
1            w          n                      w                      w   
2            w          n                      w                      w   
3            g          k                      w                      w   
4            y          n                      w                      w   
...        ...        ...                    ...                    ...   
8118         n          y                      o                      o   
8119         n          y                      o                      o   
8120         n          n                      o                      o   
8121         n          b                      w                      w   
8122         n          y                      o                      o   

     veil-color spore-print-color  
0             w                 n  
1             w                 n  
2             w                 k  
3             w                 n  
4             w                 k  
...         ...               ...  
8118          o                 b  
8119          n                 b  
8120          o                 b  
8121          w                 w  
8122          o                 o  

[8123 rows x 6 columns]

In [18]:
nomi = [name for name in column_names if 'color' not in name]
nomi

['cap-shape',
 'cap-surface',
 'bruises?',
 'odor',
 'gill-attachment',
 'gill-spacing',
 'gill-size',
 'stalk-shape',
 'stalk-root',
 'stalk-surface-above-ring',
 'stalk-surface-below-ring',
 'veil-type',
 'ring-number',
 'ring-type',
 'population',
 'habitat']

In [19]:
import numpy as np
# estraggo 3 attributi random dalla lista di nomi
random_index = np.random.randint(0,len(nomi),size=3)
attributes = [nomi[i] for i in random_index]
attributes

['stalk-surface-above-ring', 'gill-spacing', 'stalk-surface-below-ring']

In [22]:
import warnings
warnings.filterwarnings(action="ignore")
for attribute in attributes:
    # aggiungo la colonna
    mushroom_changed = mushroom_color.join(mushroom.loc[:,attribute])

    enc = OneHotEncoder(sparse=False)
    mushroom_changed_trasform = enc.fit_transform(mushroom_changed)

    print('result of the model with the attribute:',attribute)
    for name,model in zip(names,classifiers):
        scoring_model = cross_validate(model, mushroom_changed_trasform, target, scoring=scoring, cv=5)
        print('scores of '+ name +':' )
        print(scoring_model['test_accuracy'])
    print('\n')

result of the model with the attribute: stalk-surface-above-ring
scores of Random Forest:
[0.74707692 0.96369231 0.96061538 0.99568966 0.63669951]
scores of KNN:
[0.74707692 0.98584615 0.96492308 1.         0.71305419]
scores of SVC:
[0.73415385 0.99015385 0.96615385 1.         0.61761084]


result of the model with the attribute: gill-spacing
scores of Random Forest:
[0.76061538 0.99446154 0.95569231 1.         0.66995074]
scores of KNN:
[0.75569231 0.99507692 0.99507692 1.         0.658867  ]
scores of SVC:
[0.73415385 0.99015385 0.97907692 1.         0.52894089]


result of the model with the attribute: stalk-surface-below-ring
scores of Random Forest:
[0.75692308 0.95446154 0.96615385 0.9932266  0.67364532]
scores of KNN:
[0.74707692 0.976      0.96430769 0.99568966 0.68842365]
scores of SVC:
[0.73415385 0.99015385 0.92369231 1.         0.52894089]




# 7 Usare un algoritmo di regressione per calcolare il valore di edibile. Usare un train/test del 30%. Arrotondare all’intero più vicino. Cambia il risultato?

In [34]:
target_bool = target == 'e'
target_bool

0        True
1        True
2       False
3        True
4        True
        ...  
8118     True
8119     True
8120     True
8121    False
8122     True
Name: p, Length: 8123, dtype: bool

In [39]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error


X_train, X_test, y_train, y_test = train_test_split(X, target_bool, test_size=0.3,
                                                    random_state=0)
model = RandomForestRegressor(n_estimators=20,random_state=0)

model.fit(X_train,y_train)
pred = model.predict(X_test)

pred

array([1., 1., 1., ..., 0., 0., 0.])

In [ ]:
# valutiamo
score = mean_absolute_error(y_test,pred)
print("MAE:",score)